### ISSUE TITLE
Effective changelog desperately needed! (started as: "SWBFRNT2.ELF.cht not working")

### ISSUE THREAD

**Issue by suLac4ever** [PS2-Widescreen/OPL-Widescreen-Cheats#12]
First of all I want to say THANK YOU for your amazing service you did the community by creating this repository!
I enjoy the widescreenpatches very much!

### Now to the problem I noticed:

For starters the name of the cheatfile is obviously wrong: PS2rd in OPL cannot associate "SWBFRNT2.ELF.cht" with the game, because the file isn't named after the GAMEID -> "error, cannot load cheat file".

I tried changing the name of the file to the correct name (SLUS_212.40.cht) but this did absolutely nothing.

I then proceeded to **try out different master codes** both by extracting the elf from my own game with "elf_extract" and then use "**Mastercode_Finder**" to get the codes and also compared it with the codes here: [PS2-Home](https://www.ps2-home.com/forum/viewtopic.php?t=10939).
Nothing worked.

I then reconverted the widescreen patch codes again from the pnach source file but they are correct as far as I've seen.
Maybe the problem is with "SWBFRNT2.ELF" which isn't the main ELF of the game? Sadly the source doesn't state which ELF the original codes where created for.

SLES_535.03 on the other hand (also from this repository) worked perfectly ... but then its cheat file was named correctly from the start.
So something definetly doesn't seem right with "SWBFRNT2.ELF.cht".
Why is the cheat file for SLUS_212.40 not named after the GAMEID?

Do you guys know what the problem might be and maybe also able to fix it?
Or is there anything special to do in the case of SLUS_212.40 to get it to work?

**Comment by israpps** [comment]
Hi!

That one comes from the first package that I used to make this cheat repository...
So i don't know the reasons for this filename...
The only thing that comes to my mind is someone setting on OPL this ELF as the custom game ID?

**Comment by israpps** [comment]
There was another cheat with this same issue

It seems that the widescreen hack is the same for both SWFRNT2.ELF and the real program, only mastercde should differ

**Comment by suLac4ever** [comment]
I see you already changed the cht file an uploaded a new archive, thank you!

Now it would be great if there was any documentation of which you've changed with the new release, because checking multiple hundred of cht files for changes is quite impractical.

Or did I overlook something? :)

**Comment by israpps** [comment]
> I see you already changed the cht file an uploaded a new archive, thank you!
> 
> Now it would be great if there was any documentation of which you've changed or added with the new release, because checking multiple hundred of cht files for changes is quite impractical. Especially if there where any changes made to an already existing file.
> 
> Just overwriting everything is not an option for people who use other cheats as well or in my case controller remapping via cheat.
> 
> Or did I overlook something? :)

Check the git history?

**Comment by suLac4ever** [comment]
> > I see you already changed the cht file an uploaded a new archive, thank you!
> > Now it would be great if there was any documentation of which you've changed or added with the new release, because checking multiple hundred of cht files for changes is quite impractical. Especially if there where any changes made to an already existing file.
> > Just overwriting everything is not an option for people who use other cheats as well or in my case controller remapping via cheat.
> > Or did I overlook something? :)
> 
> Check the git history?

Oh, I didn't know that something like this existed. After some searching I found something.
You mean here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/commits/main ?

**Comment by suLac4ever** [comment]
By the way: I tried the new cht file for Battlefont II US but it still doesn't work ... but I was unsure if it was supposed to work now (?).

**Comment by suLac4ever** [comment]
Hey :)

**Thank you so much for including a changelog to your latest rellease!**

It would be very helpful too, if you could keep the older additions also for more easy of checking for updates.
For this time I double checked the change list with the git history and it appears, as their was no additional release between 2022-09-01 and 2022-08-24. But if theire was I would have missed it, because the latest file only contains the changes from itself not from previous releases. If you would keep previeous versions of the cheat zip, one could check the changelog of older files also, which woulddn't cause you any additional work.
In fact you would save a tiny bit of time, because you wouldn't have to delet the previous one, by also providing your repository with some additional history and transparancy. **So please keep older versions :)**

**I also checked, if I could help with any game, which needs testing and/or addition of its mastercode** ... sadly among my 216 there is non which is on your "need testing and a mastercode" list.

**Comment by israpps** [comment]
HI!
Thanks for offering your help!

Regarding storing older cheats packages...

There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date

**Comment by suLac4ever** [comment]
> HI! Thanks for offering your help!
> 
> Regarding storing older cheats packages...
> 
> There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> 
But by downloading those I don't get you list of changes, which are only in the description text of the release post here:
https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases#:~:text=latest%20changes%3A,now%20changelog%20works
You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)

> To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> 
> ```
> https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> ```
Brings up an "404: Not Found" message for me.

**Comment by israpps** [comment]
> > HI! Thanks for offering your help!
> 
> No problem! :) Sadly I couldn't really do much :/
> 
> > Regarding storing older cheats packages...
> > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> 
> But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> 
> > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > ```
> > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > ```
> 
> Brings up an "404: Not Found" message for me.

The list of changes is generated by git

```
git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
```

**Comment by suLac4ever** [comment]
> > > HI! Thanks for offering your help!
> > 
> > 
> > No problem! :) Sadly I couldn't really do much :/
> > > Regarding storing older cheats packages...
> > > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> > 
> > 
> > But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> > > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > > ```
> > > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > > ```
> > 
> > 
> > Brings up an "404: Not Found" message for me.
> 
> The list of changes is generated by git
> 
Got it working now, my mistake. I copied the wrong string (the short one), not the "full SHA".

> ```
> git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
> ```
I truthfully don't know what I have to do with that. And so many other more casual github users also wont. For this reason it would be a much simpler solution to just keep the list of older releases, like the majority of all gits do.

**Comment by israpps** [comment]
> > > > HI! Thanks for offering your help!
> > > 
> > > 
> > > No problem! :) Sadly I couldn't really do much :/
> > > > Regarding storing older cheats packages...
> > > > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> > > 
> > > 
> > > But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> > > > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > > > ```
> > > > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > > > ```
> > > 
> > > 
> > > Brings up an "404: Not Found" message for me.
> > 
> > 
> > The list of changes is generated by git
> 
> Got it working now, my mistake. I copied the wrong string.
> 
> > ```
> > git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
> > ```
> 
> I truthfully don't know what I have to do with that. And so many other more casual github users also wont. For this reason it would be a much simpler solution to just keep the list of older releases, like the majority of all gits do.

There is one problem

Adding the changelog into the Readme will polute the git history more... actually, that´s the current issue with the cheat lists...

I Could add it as an asset...

**Comment by suLac4ever** [comment]
> > > > > HI! Thanks for offering your help!
> > > > 
> > > > 
> > > > No problem! :) Sadly I couldn't really do much :/
> > > > > Regarding storing older cheats packages...
> > > > > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> > > > 
> > > > 
> > > > But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> > > > > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > > > > ```
> > > > > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > > > > ```
> > > > 
> > > > 
> > > > Brings up an "404: Not Found" message for me.
> > > 
> > > 
> > > The list of changes is generated by git
> > 
> > 
> > Got it working now, my mistake. I copied the wrong string.
> > > ```
> > > git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
> > > ```
> > 
> > 
> > I truthfully don't know what I have to do with that. And so many other more casual github users also wont. For this reason it would be a much simpler solution to just keep the list of older releases, like the majority of all gits do.
> 
> There is one problem
> 
> Adding the changelog into the Readme will polute the git history more... actually, that´s the current issue with the cheat lists...
> 
I see ...
And keeping older releases would do the same thing?
... or why don't you want to do it that way?

> I Could add it as an asset...
Adding it as an assets would be a good alternative
a kinda growning document which lists all past changes something like this
_changes 2022-09-01: ... <list>
changes 2022-08-24: ... <list>
chnages xyz: ... <list>_
by which one could keep track of the consecutive as well as continuous history and "growth" of the cheat package)

**Comment by suLac4ever** [comment]
> > > > > > HI! Thanks for offering your help!
> > > > > 
> > > > > 
> > > > > No problem! :) Sadly I couldn't really do much :/
> > > > > > Regarding storing older cheats packages...
> > > > > > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> > > > > 
> > > > > 
> > > > > But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> > > > > > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > > > > > ```
> > > > > > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Brings up an "404: Not Found" message for me.
> > > > 
> > > > 
> > > > The list of changes is generated by git
> > > 
> > > 
> > > Got it working now, my mistake. I copied the wrong string.
> > > > ```
> > > > git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
> > > > ```
> > > 
> > > 
> > > I truthfully don't know what I have to do with that. And so many other more casual github users also wont. For this reason it would be a much simpler solution to just keep the list of older releases, like the majority of all gits do.
> > 
> > 
> > There is one problem
> > Adding the changelog into the Readme will polute the git history more... actually, that´s the current issue with the cheat lists...
> 
> I see ... And keeping older releases would do the same thing? ... or why don't you want to do it that way?
> 
> > I Could add it as an asset...
Adding it as an assets would be a good alternative
a kinda growning document which lists all past changes something like this
_changes 2022-09-01: ... 
changes 2022-08-24: ... 
chnages xyz: ... _
by which one could keep track of the consecutive as well as continuous history and "growth" of the cheat package)

**Comment by suLac4ever** [comment]
> > > > > HI! Thanks for offering your help!
> > > > 
> > > > 
> > > > No problem! :) Sadly I couldn't really do much :/
> > > > > Regarding storing older cheats packages...
> > > > > There is no need for that, as you can download them by traversing to a previous commit and downloading the whole repository from that date
> > > > 
> > > > 
> > > > But by downloading those I don't get you list of changes, which are only in the description text of the release post here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases You could of course add the "latest changes" list in the readme provided with each release, but this would mean extra work for you, compared to just keeping the previous releases with their list of changes included in the post as you did with you latest release ... which again is VERY HANDY ;)
> > > > > To do so copy this URL and replace the `SHA` word with the commit hash you want to download
> > > > > ```
> > > > > https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/archive/SHA.zip
> > > > > ```
> > > > 
> > > > 
> > > > Brings up an "404: Not Found" message for me.
> > > 
> > > 
> > > The list of changes is generated by git
> > 
> > 
> > Got it working now, my mistake. I copied the wrong string.
> > > ```
> > > git --no-pager log --pretty=format:"- %h  %<(18)%an: %s">>latest_changes.log
> > > ```
> > 
> > 
> > I truthfully don't know what I have to do with that. And so many other more casual github users also wont. For this reason it would be a much simpler solution to just keep the list of older releases, like the majority of all gits do.
> 
> There is one problem
> 
> Adding the changelog into the Readme will polute the git history more... actually, that´s the current issue with the cheat lists...
> 
I see ...
And keeping older releases would do the same thing?
... or is there another reason why you don't want to keep older releases?

> I Could add it as an asset...

Adding it as an assets would be a good alternative
a kinda growning document which lists all past changes something like this
_changes 2022-09-01: ... <list>
changes 2022-08-24: ... <list>
chnages xyz: ... <list>_
by which one could keep track of the consecutive as well as continuous history and "growth" of the cheat package

**Comment by suLac4ever** [comment]
Thank you for coninouesly trying to provide some kind of useful changelog!

However the last change to your repository (the addition of the extra file, which lists changes) isn't very useful. In fact I percieve it as a step back. The file doen't contain a complete changelog, but only a summery/overview of the changes made to this repository. This isn't useful information at all.

A detailed **list of all consecutive releases by date with their detailed list of changes each** is nessesary for mere mortals to keep track of which files you've added or updated. This would enable users to keep their OPL folders updated easily whenever you update this repository. If you don't add something like this, doing that (updating private/individual OPL folders) it will stay as tremedously tedious as it at the moment, which will make this repository far less useful, as it could be.

**Example of an useful list:
_release 2022-09-13:
updated xy
added xz
added zy
updated xx
release 2022-08-24:
updated yz
updated xy
added xz_

This could easily be accomplished by – again – keeping all releases listed here:
https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases
... and setting up your repository in a way, that github automatically generates a list of all changes ("updated ..., added ...,"), which then is included in the description of every release.**

I still don't get, why you don't just do it this way, for it would be the single most easiest solution to the problem. _Seriously, why? I really would like to understand, why you don't do it that way!_
It's the easy and obvious way, which github already provided functionality for a good reason: because it is indeed useful and just makes sense.
But whatever way you choose: The present one is very far from useful. When you next try another solution, please consider my example of an actually useful list above.

**Comment by israpps** [comment]
> Thank you for coninouesly trying to provide some kind of useful changelog!
> 
> However the last change to your repository (the addition of the extra file, which lists changes) isn't very useful. In fact I percieve it as a step back. The file doen't contain a complete changelog, but only a summery/overview of the changes made to this repository. This isn't useful information at all.
> 
> A detailed **list of all consecutive releases by date with their detailed list of changes each** is nessesary for mere mortals to keep track of which files you've added or updated. This would enable users to keep their OPL folders updated easily whenever you update this repository. If you don't add something like this, doing that (updating private/individual OPL folders) it will stay as tremedously tedious as it at the moment, which will make this repository far less useful, as it could be.
> 
> **Example of an useful list: _release 2022-09-13: updated xy added xz added zy updated xx release 2022-08-24: updated yz updated xy added xz_
> 
> This could easily be accomplished by – again – keeping all releases listed here: https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/releases ... and setting up your repository in a way, that github automatically generates a list of all changes ("updated ..., added ...,"), which then is included in the description of every release.**
> 
> I still don't get, why you don't just do it this way, for it would be the single most easiest solution to the problem. _Seriously, why? I really would like to understand, why you don't do it that way!_ It's the easy and obvious way, which github already provided functionality for a good reason: because it is indeed useful and just makes sense.
> 
> But whatever way you choose: The present one is very far from useful. When you next try another solution, please consider my example of an actually useful list above.

I always try to keep git history as clean as I can...

You can keep track of when a file was changed from here on GitHub.

Also, i don't have the time to manually list all changed files

**Comment by israpps** [comment]
This could work...

https://gist.github.com/arnold-almeida/209795

Will try it when I have time...

And storing lots of releases on GitHub isn't a good idea, since storage quota is limited

**Comment by israpps** [comment]
@suLac4ever check latest package

**Comment by suLac4ever** [comment]
Hey, that looks very promising! Thank you for your patience and stamina regarding this case :)
I will see next time when there is an content update, if this full changelog is as useful as it promises to be in practice, but I think it indeed could be.
'Til then :)
