### ISSUE TITLE
Resident Evil Outbreak File #2 (SLES_533.19)

### ISSUE THREAD

**Issue by holictsubasa** [PS2-Widescreen/OPL-Widescreen-Cheats#28]
Only the first has a widescreen patch

**Comment by israpps** [comment]
So, this is a cheat request?

**Comment by holictsubasa** [comment]
yes, sorry, I'm not an expert in github.

I have made my own cht that seems to work, but I don't know how to contribute.

**Comment by israpps** [comment]
Fixed on #29
