### ISSUE TITLE
EU Widescreen codes

### ISSUE THREAD

**Issue by DieSkaarj** [PS2-Widescreen/OPL-Widescreen-Cheats#4]
Hi there,

I made a few EU codes and ported others a couple of years back: https://github.com/DieSkaarj/OpenPS2LoaderWidescreenCheats 

Please, feel free to include them in your archives.

Thanks!
David

**Comment by israpps** [comment]
added the files that weren't already here on commit a0be87b38aebd9c43b484ca9859dfe080deb9341


Thanks for opening this issue!!!
