### ISSUE TITLE
SLUS_202.59 Wizardry: Tale of the Forsaken Land (US version) won't recognize widescreen patch

### ISSUE THREAD

**Issue by Gamerhenky** [PS2-Widescreen/OPL-Widescreen-Cheats#44]
Serial code is SLUS-20259, and CRC is DD11BEF7. Tried adding //ELF CRC on .cht file but won't recognize the file no matter what, or it was an emulator issue? The European version (SLES-51118) does actually recognize however.
![Screenshot_20230213-080203](https://user-images.githubusercontent.com/37840226/218349742-ffc62981-d30c-4d06-ab72-844eb176d0fe.png)

**Comment by israpps** [comment]
Hi!

confirmation on real hardware would be nice.

i've checked [that cheat file](https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/blob/main/CHT/SLUS_202.59.cht).

only two cheats, the widescreen cheat and the mastercode. it will be easy to troubleshoot

**Comment by lichtmetzger** [comment]
> confirmation on real hardware would be nice.

The cheatfile works on a real PS2. It hangs for a very long time on a blackscreen before the game actually starts but then it works.
