### ISSUE TITLE
[FR]: cheat_list.MD with direct links to their cheat files

### ISSUE THREAD

**Issue by israpps** [PS2-Widescreen/OPL-Widescreen-Cheats#58]
### Discussed in https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **Slider2k** June 16, 2023</sup>
Could you please add direct links to CHT files in cheat_list.MD? Would greatly help in navigation!</div>

**Comment by Slider2k** [comment]
Thank you! I think it might be better to just hyperlink the game IDs (second column) instead of adding an additional column with links.

**Comment by israpps** [comment]
> Thank you! I think it might be better to just hyperlink the game IDs (second column) instead of adding an additional column with links.

Yeah. I couldnt remember how to do it with sed so i made it with what i remembered...

Maybe ill check it after some relaxing. or maybe in few days

**Comment by Slider2k** [comment]
Try this:
`sed "s/\(...._...\...\).*$/[\1](.\/CHT\/\1.cht) | [RAW](..\/..\/raw\/main\/CHT\/\1.cht)/" cheat_list.MD`

**Comment by israpps** [comment]
fixed
