### ISSUE TITLE
folder file limit?

### ISSUE THREAD

**Issue by filevans** [PS2-Widescreen/OPL-Widescreen-Cheats#67]
when copying and pasting the whole package, as the guide recommends, it doesn't work copy everything, there are over 3000 files and there seems to be a folder file limit when reading / copying. After copying, all the SLUS ones are missing, as though it can only see the first half of the files in the folder

**Comment by israpps** [comment]
I've been managing this responsibility since his creation

Never encountered a single issue related to file limit per folder

I'm using windows tho. Not sure about Linux (I guess it has no issues too)

**Comment by filevans** [comment]
what has windows or linux got to do with it?  the problem occurs in wlaunchelf when copying the CHT folder from usb to hdd, there is no error but afterwards not all the files are in the folder on the HDD

**Comment by israpps** [comment]
> what has windows or linux got to do with it? the problem occurs in ulaunchelf when copying the CHT folder from mass/usb to hdd, there is no error but afterwards not all the files appear in the folder on the HDD, so there seems to be a file copying/reading limit in ulaunchelf or the ps2 file system

Sorry! Forgot the mind reading device at home. 
Didn't saw any mention of wLaunchELF or transferring to HDD on the issue report initial comment 

***
You could use HDL batch installer partition mount feature

Or try a decent wLaunchELF version in case you're using old wLaunchELF or the latest official one

Maybe [try my mod](https://www.psx-place.com/resources/wlaunchelf-4-43x_isr.1112/download?version=2566) in case you don't wanna use HDL batch installer

**Comment by filevans** [comment]
and do i have to read your mind where you say in your guide to "paste the whole package to hdd"? you don't explain how to do it hatsover, no mention of how or what program to use, i thought ulaunchelf was the standard way o paste files onto a ps2 hdd

it was still obvious by what i said it wouldn't be referring to a file fodder limit with windows or linux, far more probable would be a file limitation on ps2 hardware over 20 years old vs a modern OS

**Comment by filevans** [comment]
> HDL batch installer partition mount feature

do you have a quick guide how i can use this to copy all of the widescreen cheats please? is it simple? as i've never used the program, i normally use WinHIIP to copy my games
thanks

**Comment by israpps** [comment]
> > HDL batch installer partition mount feature
> 
> do you have a quick guide how i can use this to copy all of the widescreen cheats please? is it simple? as i've never used the program, i normally use WinHIIP to copy my games thanks

There's no need for a guide. The UI is self explanatory. You simply have to install the Dokan driver

After that from within HDL batch installer, the mount partition feature will allow you to pick a partition from the PS2 hard drive and expose it as a Windows native drive. Then toss the files

**Comment by filevans** [comment]
well that is a guide isn't it!? that's all I asking for
