### ISSUE TITLE
Silent Hill 2 widescreen patch problem

### ISSUE THREAD

**Issue by filevans** [PS2-Widescreen/OPL-Widescreen-Cheats#69]
hello, the Silent Hill 2 widescreen patch seems to stop the highlighter working on the memo screen so you can't see which memo you have selected:

![6dd5fc28-c09b-4c3e-a8c3-aa16bf0c71b1](https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats/assets/14978933/122ecfa5-7aa1-40b7-a041-41e9642b1145)

**Comment by Saint-Fall** [comment]
Had this issue as well and found the solution back then (for SLUS_202.28). The current code under "//black borders fix" is the reason why it happens. In the cheat file replace the line 

201b8a9c 86a20010 with the following code:

201bd914 1000003a

With this one the cutscene borders are still gone, however the green background highlighter in the menu is available now.
