### ISSUE TITLE
Castlevania Lament of Innocence SLUS_207.33 Not Working

### ISSUE THREAD

**Issue by kodatarule** [PS2-Widescreen/OPL-Widescreen-Cheats#8]
As the title explains, the widescreen hack is not working at all.

**Comment by israpps** [comment]
> As the title explains, the widescreen hack is not working at all.

Could you elaborate more?

It doesn't work?
It stretches unproperly?
it affects game frame rate?

**Comment by kodatarule** [comment]
Neither of all those, it's as if it doesn't load at all hence why I didn't put any other info details

**Comment by israpps** [comment]
> Neither of all those, it's as if it doesn't load at all hence why I didn't put any other info details
> 
> Edit: game remains in 4:3 standard aspect ratio Edit2: if it helps - OPL 1.2.0 daily beta, FMCB 1.952, PS2 Slim, can confirm that for the other games I've tried widescreen works flawlessly

OPL Daily builds?

Thats a crappy & poorly maintained fork

Please try [__official beta versions__](https://github.com/ps2homebrew/Open-PS2-Loader/Releases)

**Comment by kodatarule** [comment]
So I tried with the official beta versions for both 1.1.0 and the upcoming 1.2.0 with the same results.
Is there a way to get logging or something ?

**Comment by israpps** [comment]
Hi

Yes, you can see log via ps2link...

But that won't be useful here ...

I believe that either the widescreen cheat is broken or the mastercode is not the proper one...

**Comment by israpps** [comment]
> So I tried with the official beta versions for both 1.1.0 and the upcoming 1.2.0 with the same results. Is there a way to get logging or something ?
> 
> EDIT: Just to be on the safe side I wiped out all of the configs from using OPL Daily Builds and straight up tried cleanly each OPL version and the results were the same.

Maybe you could get the game image, extract the main ELF and run mastercodefinder on it...

Then provide me the results

Beef mustard gold is different I can merge it

**Comment by kodatarule** [comment]
The master code is the correct one, also I tried manually converting the pnach file and putting those, but that ends up the picture being black with everything in the middle stretched horizontally like a line nothing visible

**Comment by kodatarule** [comment]
> > So I tried with the official beta versions for both 1.1.0 and the upcoming 1.2.0 with the same results. Is there a way to get logging or something ?
> > EDIT: Just to be on the safe side I wiped out all of the configs from using OPL Daily Builds and straight up tried cleanly each OPL version and the results were the same.
> 
> Maybe you could get the game image, extract the main ELF and run mastercodefinder on it...
> 
> Then provide me the results
> 
> Beef mustard gold is different I can merge it

Managed to get widescreen working using this cheat:
```"Castlevania: Lament of Innocence (SLUS-20733)"

Mastercode
906F6098 0C1BD7CE

Gameplay
206e70f4 3c013f40
206e70f8 44810000
206e7100 4600c602

Item_Pos-X_Fix
207b87b0 43100000
206cef54 3c014294

FMV's_Fix
204511d0 24057300
204511d4 24062000
204511dc 24071b00```

**Comment by israpps** [comment]
Would you mind doing a pull request?

So your profile gets added as collaborators
